server:
  port: 8000
spring:
  profiles:
    active: @profile.active@
    include: feign
  application:
    name: service-order
  cloud:
    nacos:
#      discovery:
        #注册到指定的命名空间 默认是注册到public
#        namespace: @profile.active@
        #修改服务注册到nacos上分组名称，默认是DEFAULT_GROUP
#        group: order

      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        namespace: ${spring.profiles.active:public}

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: dev

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
      - nacos:haha.properties?group=order
    activate:
      on-profile: test

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
      - nacos:hehe.properties?group=order
    activate:
      on-profile: prod